### PR TITLE
First Non Repeated Exercise Response

### PR DESCRIPTION
**Pull request by amymariewall**
This is still failing 4 out of the 5 tests.

However, it _is_ working for me when I run it in repl.it. I am using "puts first_non_repeated_letter" (".....") and copying and pasting the various strings you provided in the exercise into the parentheses.

My work on repl.it is here: https://repl.it/BdUf/8

This was my thought process:

1) Turn the string into an array
2) See if the element in position 1 is the same as the element in position 0.
-If it is not, return the element in position 0 and stop.
-If it is, continue
3) Loop through the elements of the array (except the first and last elements) and compare them with the element directly preceding them and the element directly succeeding them to test for equality. If an element is not equal to the element preceding it and also not equal to the element succeeding it, return that element and stop. Otherwise, continue.
4) See if the last element in the array is the same as the element directly preceding it. If not, return the last element and stop.
5) Put nil if nothing got returned.

### CODE REVIEW

**Comment by sumeetjain** [comment]
It can be helpful to go through your algorithm with an example input. I'm going to that below (and I've copy/pasted your code for easy reference). Let's say our input `str` is `"aabbcd"` (so `"c"` is the first non-repeated letter).

``` ruby
def find_first_non_repeated_letter(str)
    new_array=[]
    new_array=str.split""
    (1..(new_array.length-1)).each do |i|
        if new_array[0] != new_array[1]
            return new_array[0]
        elsif new_array[i] != new_array[i-1] && new_array[i] != new_array[i+1]
            return new_array[i]
        elsif new_array.last != new_array[new_array.length-1]
            return new_array.last
        else
            return nil
        end
    end
end
```

| line(s) of code | result |
| --- | --- |
| N/A | Before beginning, we know that `str` is `"aabbcd"` |
| `new_array=[]` | `new_array` is `[]` |
| `new_array=str.split""` | Just kidding! `new_array` is `["a", "a", "b", "b", "c", "d"]` |
| `(1..(new_array.length-1)).each` | `new_array.length` would be `6`, so we're setting up a loop to run 6 times. I'm going to start a new table for this loop. See the below table. |

Okay, so this next table represents what happens during _each_ iteration of the `(1..(new_array.length-1)).each` loop you wrote. `i` represents the current "iteration" number that is being executed.

At the time this code begins, `new_array` is `["a", "a", "b", "b", "c", "d"]`

| Current value of `i` | Code | Notes |
| --- | --- | --- |
| 1 | `if new_array[0] != new_array[1]` | So `"a" !=`"a"`. They are the same, so that code returns`false`. |
| 1 | `elsif new_array[i] != new_array[i-1] && new_array[i] != new_array[i+1]` | So if `"a" != "a" && "a" != "b"`. `false` again. |
| 1 | `elsif new_array.last != new_array[new_array.length-1]` | So if `"d" != "c"`. That's `true'! So... |
| 1 | `return new_array.last` | Return `"d"` |

A `return` indicates the _end_ of the algorithm, so Ruby will stop there. The returned value is `"d"`, but that's not what we were hoping for! We wanted `"c"`.

Looking at your code, it seems that you were expecting the `elsif new_array[i] != new_array[i-1] && new_array[i] != new_array[i+1]` part to run for each number in the array... But you only wanted the other parts to run once–at certain times. That is, you wanted the steps of your code to run according to the following:

Code | When you wanted it to run (and how many times)
`new_array[0] != new_array[1]` | Run this once, before doing anything else.
`new_array[i] != new_array[i-1] && new_array[i] != new_array[i+1]` | Run this for each number (except the first number and last number)
`new_array.last != new_array[new_array.length-1]` | Run this once, after trying all of the other checks.

But your code wasn't written as such. Does the above explanation make sense? Let me know if I can further explain–sometimes I overexplain or underexplain, so feedback from you will help me a lot.

**Comment by amymariewall** [comment]
Yes! That explanation makes sense and is _extremely_ helpful. Thank you.

The reason I put both new_array=[] AND new_array=str.split"" was because I thought I had to "initialize" or "define" the array or something first. 

By using (1..(new_array.length-1)).each, I was not intending to write a loop that ran 6 times. Instead, I was trying to loop through all the elements in new_array except for the first element and the last element. To do this, I was trying to create a range from position 1 to position (last-1), and run the loop only on the elements of my array that fell within that range.

YES, you are correct that I wanted to run the first bit of code and stop if it found something to return. Then continue to the next bit of code and stop if it found something to return, and only continue to the last bit of code if it didn't find anything in the two prior bits of code.

I will take a look at my if/else statements and my loop to see if I can get this working properly.

**Comment by sumeetjain** [comment]
Sounds good!

**Comment by amymariewall** [comment]
I do have one more question:

You said in your table that, when testing i=1 for ["a", "a", "b", "b", "c", "d"]:
"elsif new_array.last != new_array[new_array.length-1]  So if "d" != "a". That's `true'! So..."

But I don't understand why it would have compared "a" with anything in that. This was just supposed to compare the last element with the second-to-last element.

**Comment by sumeetjain** [comment]
Ah, you are right. That's my mistake. I've fixed it now.

**Comment by amymariewall** [comment]
But why would it still return "d"? it was only supposed to return new_array.last if the condition was met, otherwise it was supposed to move on and return "nil". I think perhaps I am using return incorrectly...

**Comment by amymariewall** [comment]
NOPE I take back that question. I get that part.

**Comment by sumeetjain** [comment]
:smile:

**Comment by sumeetjain** [comment]
Just checking in Amy. How's it going? (Not trying to add pressure. Consider this a gentle reminder.)

**Comment by amymariewall** [comment]
Thanks for checking in on this. I have abandoned this approach and instead am tackling it this way:

1) Create an array that contains the index of every occurrence of a character in the given string.
2) Check to see if the difference between two adjacent indices is greater than 1 (or if there is only one element in the returned array).
3) Return the first character that meets those conditions.

I haven't gotten the code working yet...but I think I'm getting there. I will submit my progress on it shortly. 

I am just finishing up my FINAL day of work at my current job, so thankfully I will have a lot more time to continue working through it.

**Comment by sumeetjain** [comment]
Roger that! Thanks for the update.

**Comment by sumeetjain** [comment]
Amy, how are things going? If you're struggling with this, let me know! I'm here to help.

**Comment by sumeetjain** [comment]
Amy, checking in–haven't heard from you. Remember that I'd like to be kept in the loop.

**Comment by amymariewall** [comment]
This should be all good now - I believe the "test with two unique" failure is okay since you mentioned that was an error in the test.

**Pull request closed without merging**
