### PR TITLE
Non-repeat

### PR DESCRIPTION
**Pull request by jillianw**
Hi Sumeet -

I'm finding this exercise pretty challenging. I gave my best shot at an algorithm below. Could you let me know if I'm at all on the right track and, if so, how I might figure out even where to begin with the ???? parts of the code? I can't think of what to Google besides "first non-repeating letter in Ruby" which is probably just going to give me the answer...
</style>
</head>
<body>

<table style="width:100%">
  <tr>
    <th>Step</th>
    <th>English</th> 
    <th>Code Ideas</th>
  </tr>
  <tr>
    <td>1</td>
    <td>Start with a string that needs checked for non-repeating characters</td> 
    <td>(str)</td>
  </tr>
  <tr>
    <td>2</td>
    <td>Create a new variable to store results of what's happening below</td> 
    <td>b = [ ]</td>
  </tr>
  <tr>
    <td>3</td>
    <td>Create a counter variable for use in upcoming loop (starts at beginning of string)</td> 
    <td>i = 0</td>
  </tr>
  <tr>
    <td>4</td>
    <td>Start a loop that checks, one-at-a-time from the beginning, if there are any non-repeating characters</td> 
    <td> ?????? </td>
  </tr>
  <tr>
    <td>5</td>
    <td>Inside the loop, change the value of i so that the next iteration of the loop deals with the next character</td> 
    <td>i = i + 1</td>
  </tr>
  <tr>
    <td>6</td>
    <td>Inside the loop, as soon as a non-repeating character is found, end the loop</td> 
    <td>??????</td>
  </tr>
 <tr>
    <td>7</td>
    <td>Result is stored in new variable</td> 
    <td>return b</td>
  </tr>
</table>

</body>
</html>

### CODE REVIEW

**Comment by sumeetjain** [comment]
This is a good start. Let's begin with the first `?????`:

> Start a loop that checks, one-at-a-time from the beginning, if there are any non-repeating characters

Without thinking specifically of code, how would you check if a given character is non-repeating? Here's an example:

`qqqwwwxxmtttty`

So–again _without_ code, just as a human–start with the first letter `q` and figure out if it's repeated.

Done? How did you do it?

Do it again for the next letter and the one after that? How did you do those? Were the processes similar at all? How so? How were they different?

These details will help you write a more specific set of steps in the algorithm, which will help because `Start a loop that checks, one-at-a-time from the beginning, if there are any non-repeating characters` is too broad to translate immediately into code.

**Comment by jillianw** [comment]
Alright, so when I look at qqqwwwxxmtttty, I quickly scan over the letters starting at the beginning. I see 3 q's and move on, I see 3 w's and move on, 2 x's and move on, then I spot the one m and know that's the character I'm looking for. 

So would we perhaps be storing the repeating characters in a different variable to get them out of the way? Or something else?

Thanks!

**Comment by sumeetjain** [comment]
> I quickly scan over the letters starting at the beginning

Let's clarify that bit even further.

If you were explaining this process to someone who didn't understand what you meant by "scan over the letters", what might you say? What kind of _flow chart_ could you draw for them to replicate the process that you know as "scan over the letters"?

**Comment by jillianw** [comment]
Sorry -- this must be painful for you! :)  I am <i>not</i> a natural algorithmic-thinker, I think, so bear with me. 

Here's my (sort of) flow chart:

Look at character 1
Look at character 2
Are they the same?
  If yes --> move on to next <i>different</i> character
  If no --> character 1 is first non-repeating character

And so on. How's that?

**Comment by sumeetjain** [comment]
(Not painful at all. You're doing fine–this stuff is tough for a lot of folks.)

---

Your algorithm:
- Look at character 1
- Look at character 2
- Are they the same?
  - If yes --> move on to next _different_ character
  - If no --> character 1 is first non-repeating character

Nice. But would it work less effectively if the algorithm was this:
- Look at character 1
- Look at character 2
- Are they the same?
  - If yes --> move on to next character
  - If no --> character 1 is first non-repeating character

(I just removed the 'different' qualifier.)

It doesn't work any less effectively, in fact. And if it's not any less effective but it _is_ simpler, then we should favor that algorithm (because it'll be easier to code).

So bringing this back to code, if you had the following array:

``` ruby
arr = ["q", "q", "q", "w", "w", "w", "x", "x", "m", "t", "t", "t", "t", "y"]
```

And were looping through it with a counter `i = 0`, you would have:

``` ruby
while i < array.length
  # Your code here.
  i = i + 1 # So that the loop moves from one character to the next.
end
```

You can access the current iteration of the loop with `arr[i]`, because `i` starts at `0` and advances by one each time.

You can even access the next iteration of the loop with `arr[i+1]` – or the previous iteration with `arr[i-1]`.

So how would you translate this algorithm into code–specifically within the context of this loop that I've started for you?

Again, the part of the algorithm we're focusing on is:
- Given a particular character (starting from the first one)...
- Look at the next character
- Are they the same?
  - If yes --> move on to next character
  - If no --> This is the first non-repeating character

See how far you can take this–I'm happy to help whenever/if you get stuck.

**Comment by jillianw** [comment]
I got a bit stuck on the line with all the question marks, so before I get too far down that rabbit hole I just wanted to do a quick check if I'm on track with the rest of it. Thanks for your help!!

**Comment by sumeetjain** [comment]
Yup, this is the right track.

It won't immediately get the right answer, but it _is_ a good process for getting there.

Let me know if I can be helpful in figuring out the code.

**Comment by jillianw** [comment]
Is this any closer or worse? I'm totally stuck. I have no idea how to tell Ruby to move on to something else if it doesn't find what it's looking for. I mean, I know that's the concept of a loop (an until loop, I think) but how to code that for this particular situation... it's just not clicking.

**Pull request closed without merging**
